pipeline {
  agent any

  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/TanushaRoy/jenkis2.git'
      }
    }

    stage('Install Dependencies') {
      steps {
        sh 'npm install'
      }
    }

    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }

    stage('Deploy') {
      steps {
        // Assuming we are deploying to /var/www/html
        sh 'sudo cp -r build/* /var/www/html/'
      }
    }
  }
}
