pipeline {
  agent any

  environment {
    REACT_APP_DIR = 'my-frontend-app'  // Optional: in case your app is inside a subfolder
  }

  stages {
    stage('Clone') {
      steps {
        git 'https://github.com/TanushaRoy/jenkis2.git'
      }
    }

    stage('Install Dependencies') {
      steps {
        dir("${REACT_APP_DIR}") {
          sh 'npm install'
        }
      }
    }

    stage('Build') {
      steps {
        dir("${REACT_APP_DIR}") {
          sh 'npm run build'
        }
      }
    }

    stage('Deploy') {
      steps {
        dir("${REACT_APP_DIR}") {
          sh 'sudo cp -r build/* /var/www/html/'
        }
      }
    }
  }
}
